### PR TITLE
Add nodes API controller

### PR DESCRIPTION
**Pull request by tvdeyen**
Adds a node endpoint and adds the page relation to the node serializer.

### CODE REVIEW

**Review by mamhoff — APPROVED** [review]
I think you might want to include the `page` relationship by default?

**Comment by tvdeyen** [comment]
> I think you might want to include the `page` relationship by default?

Because a node without a page is nothing? That's not necessarily true. A node is just a name and an url. The url might come from the optional page, but doesn't have to.

**Comment by tvdeyen** [comment]
Speaking of, we might want to add a page- and element-type filter? But we can do that later

**Comment by mamhoff** [comment]
I meant that the serializer accesses the page, whether you want to render it out or not, so at the database level it makes sense to include the page no matter what...

**Pull request merged**
